app:
  forwarders:
    testingForwarder:
      url: http://192.168.1.100:6666/data/report
    wetterCom:
      url: http://interface.wetterarchiv.de/weather
      userId: 21311
      idKennwort: 55d563fc78
      interval: 300
    wunderground:
      url: https://weatherstation.wunderground.com/weatherstation/updateweatherstation.php
      id: 'IHOHEN243'
      key: 'Zi5hmqr0'
      period: 300
  name: 'JWeatherFlux'
  version: '@project.version@'

management:
  endpoints:
    web:
      exposure:
        include: [health,info,prometheus]

server:
  port: 6666

spring:
  influx:
    url: http://192.168.1.1:8086
    token: "xjsX2Zqu2WmCJ3bgTjjJ7Gd8xWaqD6ic03zsHPRV7Ve5qR356T3dFRMVkDaYlBXotoUxuWawZvQQjkIvaPHGFQ=="
    org: private
    bucket: weather

---
spring:
  config:
    activate:
      on-profile: development
  influx:
    url:
app:
  name: 'JWeatherFlux'
  version: '@project.version@'
  #forwarders: []
  forwarders:
    testingForwarder:
      url:
    wunderground:
      url:
    wetterCom:
      url:
      #url: http://interface.wetterarchiv.de/weather
      #userId: 21311
      #idKennwort: 55d563fc78
      #interval: 300
    awekas:
      url: http://data.awekas.at/eingabe_pruefung.php?val=
      #id: 22303
      #key: 0Tgix069%2FyBshfSwJDb97oecN%2FlggiPpkr7WPpPrTFfGOOdraCUxNE1KtHtref0xPX6xIb18jB6dzYExXwd%2B0A%3D%3D
      id: ChrisMuc
      key: UimIWj3Ic7QvFJ22Wpcihm

      interval: 300