{
 "title": "WeatherFlux",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "query0" }
  ]
 },
 "panels": [
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "alias": "$tag_location",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperature_celsius",
     "query": "SELECT last(\"value\") FROM \"temperature_celsius\" WHERE $timeFilter GROUP BY time($__interval), \"location\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current temperature",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 2, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_location",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "location" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperature_celsius",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "alias": "$tag_location",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "location" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "humidity",
     "query": "SELECT mean(\"value\") FROM \"humidity\" WHERE $timeFilter GROUP BY time($__interval), \"location\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Wind",
   "type": "spectraphilic-windrose-panel",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "windrose_kmh",
     "query": "SELECT mean(\"speed\") as speed,mean(\"direction\") as direction FROM \"windrose_kmh\" WHERE $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Windspeed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 8 },
   "targets": [
    {
     "alias": "$tag_location",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "location" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "windspeeds_kmh",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Windrichtungen",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 8 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "winddirs",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Sonnenstrahlung",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "solarradiation",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "UV Index",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uv",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Luftdruck",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "barometer_relative_hpa",
     "query": "SELECT mean(\"value\") FROM \"measurement\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Rain",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "alias": "$tag_location",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "location" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rain_metric",
     "query": "SELECT mean(\"value\")  * 1000 FROM \"rain_metric\" WHERE $timeFilter GROUP BY time($__interval), \"location\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } }
 ]
}